apiVersion: v1
kind: Service
metadata:
  name: go
  labels:
    app: go
spec:
  ports:
  - nodePort: 32201
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go
  type: LoadBalancer
